services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  serviceprovider-service:
    build: ./serviceprovider-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:providerdb
    depends_on:
      - eureka-server

  job-service:
    build: ./job-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:jobdb
    depends_on:
      - eureka-server

  customer-service:
    build: ./customer-service
    ports:
      - "8090:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
    depends_on:
      - eureka-server
      - job-service
      - serviceprovider-service
